### ISSUE TITLE
ERROR in ./css/app.scss

### ISSUE THREAD

**Issue by wdiechmann** [qhwa/dockerize#1]
I really hate to open a new issue - when this repo is such a nice tool!!

```
mix phx.new testapp --no-ecto
cd testapp
mix dockerize.init
```
This far all is well - then I have to uncomment 3 lines in the Dockerfile to adapt to a Phoenix project - which is such a nice 'side-dish' ❤️ 

Then I set sails with `docker build .` only to have `ERROR in ./css/app.scss`

But my observation is that all I have to do is:

```
# Dockerfile
...
ADD . .
RUN cd assets && yarn --pure-lockfile && cd -
....
```

```
# .dockerignore
...
node_modules
npm-debug.log
```

If you can confirm that - I believe other devs will like you to add it to the repo 😄

**Comment by qhwa** [comment]
Hi @wdiechmann, thank you for the report! It IS a bug. You're right about the solution, just keeping `node_modules` out from the docker context. I'm going to add it to the repository, or a PR is welcome.

If you're interested, I just pushed a new branch which not only solves this issue but also brings significant faster building.

You can try with:

```
mix archive.install github qhwa/dockerize branch v0.2-dev
mix dockerize.init
DOCKER_BUILDKIT=1 docker build .
```

This approach, however, depends on [docker buildkit](https://docs.docker.com/develop/develop-images/build_enhancements/) feature, you may use it with caution because not all platform supports it yet.

Anyway, thanks for the feedback, I'm very glad to see it's being used in your project.
